// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import "efuzy/dist/types/feature-flag";

declare module "efuzy/dist/types/feature-flag" {
  interface EfuzyFeatureFlags {
    ssr: true;
  }
}
